/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto1;

import static java.lang.Float.parseFloat;
import java.text.DecimalFormat;

/**
 *
 * @author master
 */
public class UI_Interes extends javax.swing.JFrame {
    int variable;
    double aux=0;
    double var[]={0,0,0,0};
    InteresSimple Simple = new InteresSimple(var);
    InteresCompuesto Compuesto=new InteresCompuesto(var);
    
    
    DecimalFormat decimales = new DecimalFormat("0.0000");
    /**
     * Creates new form UI_Interes
     */
    public UI_Interes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        VP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        I = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        N = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Instrucciones: Llena todos los campos; Exepto el que deseas calcular.");

        jLabel2.setText("VF:");

        VF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                VFFocusLost(evt);
            }
        });
        VF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VFKeyTyped(evt);
            }
        });

        jLabel3.setText("VP:");

        VP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                VPFocusLost(evt);
            }
        });
        VP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VPKeyTyped(evt);
            }
        });

        jLabel4.setText("I:");

        I.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IFocusLost(evt);
            }
        });
        I.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IKeyTyped(evt);
            }
        });

        jLabel5.setText("N:");

        N.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NFocusLost(evt);
            }
        });
        N.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NKeyTyped(evt);
            }
        });

        jLabel6.setText("Tipo de Interés:");

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Compuesto" }));
        Tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TipoItemStateChanged(evt);
            }
        });

        jLabel7.setText("*En Decimal");

        Calcular.setText("Calcular");
        Calcular.setEnabled(false);
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(VF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(I, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(N)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(VP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(VF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VFKeyTyped
       ValidaNumero(evt);
    }//GEN-LAST:event_VFKeyTyped

    private void VPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VPKeyTyped
        ValidaNumero(evt);
    }//GEN-LAST:event_VPKeyTyped

    private void IKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IKeyTyped
        ValidaNumero(evt);
    }//GEN-LAST:event_IKeyTyped

    private void NKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NKeyTyped
        ValidaNumero(evt);
    }//GEN-LAST:event_NKeyTyped

    private void VFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VFFocusLost
        ValidaParametros();
    }//GEN-LAST:event_VFFocusLost

    private void VPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VPFocusLost
        ValidaParametros();
    }//GEN-LAST:event_VPFocusLost

    private void IFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IFocusLost
        ValidaParametros();
    }//GEN-LAST:event_IFocusLost

    private void NFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NFocusLost
        ValidaParametros();
    }//GEN-LAST:event_NFocusLost

    private void TipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoItemStateChanged
        ValidaParametros();
    }//GEN-LAST:event_TipoItemStateChanged

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        for (int i = 0; i < 4; i++) {
            if (i!=variable) {
                Simple.SetVariable(i, var[i]);
            }
        }
        
        if (Tipo.getSelectedIndex()==0) {
            
            switch(variable){
                case 0:
                    aux=Simple.CalculaVP();
                    var[variable]=aux;
                    Simple.SetVariable(variable, aux);
                    VP.setText(decimales.format(aux));
                    break;
                case 1:
                    aux=Simple.CalculaVF();
                    var[variable]=aux;
                    Simple.SetVariable(variable, aux);
                    VF.setText(decimales.format(aux));
                    break;
                case 2:
                    aux=Simple.CalculaI();
                    var[variable]=aux;
                    Simple.SetVariable(variable, aux);
                    I.setText(decimales.format(aux));
                    break;
                default:
                    aux=Simple.CalculaN();
                    var[variable]=aux;
                    Simple.SetVariable(variable, aux);
                    N.setText(decimales.format(aux));
                    break;
            }
            
        }
        else{
            switch(variable){
                case 0:
                    aux=Compuesto.CalculaVP();
                    aux=Math.round(aux*100000000d)/100000000d;
                    var[variable]=aux;
                    Compuesto.SetVariable(variable, aux);
                    VP.setText(aux+"");
                    break;
                case 1:
                    aux=Compuesto.CalculaVF();
                    aux=Math.round(aux*100000000d)/100000000d;
                    var[variable]=aux;
                    Compuesto.SetVariable(variable, aux);
                    VF.setText(aux+"");
                    break;
                case 2:
                    aux=Compuesto.CalculaI();
                    aux=Math.round(aux*100000000d)/100000000d;
                    var[variable]=aux;
                    Compuesto.SetVariable(variable, aux);
                    I.setText(aux+"");
                    break;
                default:
                    aux=Compuesto.CalculaN();
                    aux=Math.round(aux*100000000d)/100000000d;
                    var[variable]=aux;
                    Compuesto.SetVariable(variable, aux);
                    N.setText(aux+"");
                    break;
            }
        }
    }//GEN-LAST:event_CalcularActionPerformed
    
    private void ValidaNumero(java.awt.event.KeyEvent evt) {                            
        char caracter = evt.getKeyChar();
        //                   Numero                            Decimal        Negativo             Borrar
        if(((caracter < '0') || (caracter > '9')) && (caracter != '.') && (caracter != '-') && (caracter != '\b') ){
            evt.consume();  // ignorar el evento de teclado
        }
    }
    
    private void ValidaParametros(){
        
        int contador=0;
        
        //valor presente
        if (!VP.getText().isEmpty()) {
            try{
                aux=parseFloat(VP.getText());
                aux=Math.round(aux*100000000d)/100000000d;
                var[0]=aux;
                VP.setText(aux+"");
            }
            catch(Exception e){
                contador++;
            }
            
        }
        else{
            contador++;
            variable=0;
        }
        
        //valor futuro
        if (!VF.getText().isEmpty()) {
            try{
                aux=parseFloat(VF.getText());
                aux=Math.round(aux*100000000d)/100000000d;
                var[1]=aux;
                VF.setText(aux+"");
            }
            catch(Exception e){
                contador++;
            }
            
        }
        else{
            contador++;
            variable=1;
        }
        
        //Interes
        if (!I.getText().isEmpty()) {
            try{
                aux=parseFloat(I.getText());
                aux=Math.round(aux*100000000d)/100000000d;
                var[2]=aux;
                I.setText(aux+"");
            }
            catch(Exception e){
                contador++;
            }
            
        }
        else{
            contador++;
            variable=2;
        }
        
        //Numero de periodos
        if (!N.getText().isEmpty()) {
            try{
                aux=parseFloat(N.getText());
                aux=Math.round(aux*100000000d)/100000000d;
                var[3]=aux;
                N.setText(aux+"");
            }
            catch(Exception e){
                contador++;
            }
            
        }
        else{
            contador++;
            variable=3;
        }
        
       
        
        
        //validamos si habilitar el boton calcular
        if (contador == 1) {
            Calcular.setEnabled(true);
        }
        else{
            Calcular.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Interes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Interes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Interes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Interes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Interes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField I;
    private javax.swing.JTextField N;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JTextField VF;
    private javax.swing.JTextField VP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
